export const routes = [
    { parent: "Marketing", child: "" },
    { parent: "Application", child: "" },
    { parent: "Documentation", child: "" },
    { parent: "Pricing", child: "" },
    { parent: "Free", child: "" },
    { parent: "E-Commerce", child: "" },
    { parent: "Marketing", child: "Hero" },
    { parent: "Marketing", child: "Feature" },
    { parent: "Marketing", child: "CTA" },
    { parent: "Marketing", child: "FAQ" },
    { parent: "Marketing", child: "Newsletter" },
    { parent: "Marketing", child: "Stats" },
    { parent: "Marketing", child: "Testimonials" },
    { parent: "Marketing", child: "Blog" },
    { parent: "Marketing", child: "Contact" },
    { parent: "Marketing", child: "Team" },
    { parent: "Marketing", child: "Content" },
    { parent: "Marketing", child: "Pricing" },
    { parent: "Marketing", child: "Footer" },
    { parent: "Marketing", child: "Logo Cloud" },
    { parent: "Marketing", child: "Navbar" },
    { parent: "Marketing", child: "Banner" },
    { parent: "Marketing", child: "Landing" },
    { parent: "Application", child: "Stacked Layout" },
    { parent: "Application", child: "Sidebar Layout" },
    { parent: "Application", child: "Multi Column Layout" },
    { parent: "Application", child: "Page Heading" },
    { parent: "Application", child: "Card Heading" },
    { parent: "Application", child: "Section Heading" },
    { parent: "Application", child: "Description List" },
    { parent: "Application", child: "Stats" },
    { parent: "Application", child: "Stacked List" },
    { parent: "Application", child: "Grid List" },
    { parent: "Application", child: "Feed" },
    { parent: "Application", child: "Form Layout" },
    { parent: "Application", child: "Sign in" },
    { parent: "Application", child: "Radio Group" },
    { parent: "Application", child: "Action Panel" },
    { parent: "Application", child: "Alert" },
    { parent: "Application", child: "Navbar" },
    { parent: "Application", child: "Tabs" },
    { parent: "Application", child: "Vertical Nav" },
    { parent: "Application", child: "Sidebar Navigation" },
    { parent: "Application", child: "Breadcrumb" },
    { parent: "Application", child: "Steps" },
    { parent: "Application", child: "Footer" },
    { parent: "Application", child: "Dialog" },
    { parent: "Application", child: "SlideOver" },
    { parent: "Application", child: "Notification" },
    { parent: "Application", child: "Command Menu" },
    { parent: "Application", child: "Container" },
    { parent: "Application", child: "Panel" },
    { parent: "Application", child: "List Container" },
    { parent: "Application", child: "Divider" },
    { parent: "Application", child: "Dashboard" },
    { parent: "Application", child: "Detail" },
    { parent: "Application", child: "Setting" },
    { parent: "E-Commerce", child: "Product List" },
    { parent: "E-Commerce", child: "Product OverView" },
    { parent: "E-Commerce", child: "Category Preview" },
    { parent: "E-Commerce", child: "Shopping Cart" },
    { parent: "E-Commerce", child: "Category Filter" },
    { parent: "E-Commerce", child: "Product Quickview" },
    { parent: "E-Commerce", child: "Product Feature" },
    { parent: "E-Commerce", child: "Store Navigation" },
    { parent: "E-Commerce", child: "Promo Section" },
    { parent: "E-Commerce", child: "Checkout Form" },
    { parent: "E-Commerce", child: "Review" },
    { parent: "E-Commerce", child: "Order Summary" },
    { parent: "E-Commerce", child: "Order History" },
    { parent: "E-Commerce", child: "Incentive" },
    { parent: "E-Commerce", child: "Storefront" },
    { parent: "E-Commerce", child: "Product Page" },
    { parent: "E-Commerce", child: "Category Page" },
    { parent: "E-Commerce", child: "Shopping Cart Page" },
    { parent: "E-Commerce", child: "Checkout Page" },
    { parent: "E-Commerce", child: "Order Detail Page" },
    { parent: "E-Commerce", child: "Order History Page" },
];